name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint:
    name: Ruff lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python: [ '3.10.x' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
      - name: Setup poetry cache
        uses: actions/cache@v3
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      - name: Install dependencies
        run: poetry install --no-root
      - name: Lint with Ruff
        uses: chartboost/ruff-action@v1
        with:
          src: './gromp'
          args: check --target-version=py310 --fix
        continue-on-error: false

  format:
    name: Black format
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python: [ '3.10.x' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
      - name: Setup poetry cache
        uses: actions/cache@v3
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      - name: Install dependencies
        run: poetry install --no-root
      - name: Format with Black
        uses: psf/black@stable
        with:
          src: './gromp'
